# Generated by Django 5.2.17 on 2026-08-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='منطقه سازمانی کاربر؛ برای ارزیاب و سرپرست منطقه تکمیل می\u200cشود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluators', to='appraisals.region', verbose_name='منطقه'),
        ),
    ]
