# Generated by Django 5.2.17 on 2026-08-10 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="کد شعبه"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام شعبه")),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام رئیس شعبه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "شعبه",
                "verbose_name_plural": "شعب",
                "ordering": ("region__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="EvaluationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان بخش")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="آیکون"),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="ترتیب")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="وزن بخش"
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش ارزیابی",
                "verbose_name_plural": "بخش\u200cهای ارزیابی",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="کد منطقه"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام منطقه")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "منطقه",
                "verbose_name_plural": "مناطق",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("submitted", "ارسال شده"),
                            ("returned", "برگشت داده شده"),
                            ("approved", "تأیید شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("evaluation_date", models.DateField(verbose_name="تاریخ ارزیابی")),
                ("strengths", models.TextField(blank=True, verbose_name="نقاط قوت")),
                (
                    "improvements",
                    models.TextField(blank=True, verbose_name="نقاط قابل بهبود"),
                ),
                (
                    "market_opportunities",
                    models.TextField(blank=True, verbose_name="فرصت\u200cهای بازار"),
                ),
                (
                    "branch_needs",
                    models.TextField(
                        blank=True, verbose_name="درخواست\u200cها و نیازها"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="امتیاز کل",
                    ),
                ),
                (
                    "section_scores",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="امتیاز بخش\u200cها"
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="نظر بازبین"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ارزیابی",
                "verbose_name_plural": "ارزیابی\u200cها",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="عملیات")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="جزئیات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisal_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="appraisals.evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد ممیزی",
                "verbose_name_plural": "رویدادهای ممیزی",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField(verbose_name="مهلت انجام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "تخصیص داده شده"),
                            ("in_progress", "در حال انجام"),
                            ("submitted", "ارسال شده"),
                            ("returned", "برگشت داده شده"),
                            ("approved", "تأیید شده"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_assignments",
                        to="appraisals.branch",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص ارزیابی",
                "verbose_name_plural": "تخصیص\u200cهای ارزیابی",
                "ordering": ("due_date", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="evaluation",
            name="assignment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluation",
                to="appraisals.evaluationassignment",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="عنوان دوره")),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("active", "فعال"),
                            ("closed", "بسته"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_evaluation_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره ارزیابی",
                "verbose_name_plural": "دوره\u200cهای ارزیابی",
                "ordering": ("-start_date",),
            },
        ),
        migrations.AddField(
            model_name="evaluationassignment",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="appraisals.evaluationcycle",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن معیار")),
                ("order", models.PositiveSmallIntegerField(verbose_name="ترتیب")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="وزن معیار"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="الزامی"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="appraisals.evaluationsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "معیار ارزیابی",
                "verbose_name_plural": "معیارهای ارزیابی",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="عنوان")),
                ("version", models.PositiveIntegerField(verbose_name="نسخه")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("retired", "بازنشسته"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ اجرا"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_evaluation_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "الگوی ارزیابی",
                "verbose_name_plural": "الگوهای ارزیابی",
                "ordering": ("-version",),
            },
        ),
        migrations.AddField(
            model_name="evaluationsection",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="appraisals.evaluationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="evaluationcycle",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cycles",
                to="appraisals.evaluationtemplate",
            ),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_name",
                    models.CharField(max_length=250, verbose_name="نام سازمان"),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد کارکنان"
                    ),
                ),
                (
                    "opportunity_types",
                    models.JSONField(default=list, verbose_name="انواع فرصت"),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="مسئول پیگیری"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=150, verbose_name="وضعیت"),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ هدف"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="appraisals.evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرصت منطقه",
                "verbose_name_plural": "فرصت\u200cهای منطقه",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches",
                to="appraisals.region",
            ),
        ),
        migrations.CreateModel(
            name="RegionSupervisorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_assignments",
                        to="appraisals.region",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_region_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص سرپرست منطقه",
                "verbose_name_plural": "تخصیص\u200cهای سرپرستان مناطق",
            },
        ),
        migrations.CreateModel(
            name="EvaluationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField(verbose_name="امتیاز")),
                (
                    "weighted_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="امتیاز وزنی",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="appraisals.evaluation",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="appraisals.evaluationcriterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ ارزیابی",
                "verbose_name_plural": "پاسخ\u200cهای ارزیابی",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evaluation", "criterion"),
                        name="unique_evaluation_criterion_answer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                        name="answer_score_between_1_and_5",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="evaluationassignment",
            constraint=models.UniqueConstraint(
                fields=("cycle", "branch"), name="unique_branch_assignment_per_cycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationcriterion",
            constraint=models.UniqueConstraint(
                fields=("section", "order"), name="unique_section_criterion_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationtemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_evaluation_template_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationsection",
            constraint=models.UniqueConstraint(
                fields=("template", "order"), name="unique_template_section_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="regionsupervisorassignment",
            constraint=models.UniqueConstraint(
                fields=("region", "supervisor"),
                name="unique_region_supervisor_assignment",
            ),
        ),
    ]
